# 3. Neural Network

In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([7, 8])

print(a.shape)
print(b.shape)
np.dot(a, b)

(3, 2)
(2,)


array([23, 53, 83])

In [12]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8]])

print(a.shape)
print(b.shape)
np.dot(a, b)

(3, 2)
(1, 2)


ValueError: shapes (3,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

In [5]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7], [8]])

print(a.shape)
print(b.shape)
np.dot(a, b)

(3, 2)
(2, 1)


array([[23],
       [53],
       [83]])

In [6]:
a = np.array([7, 8])
b = np.array([[1, 2], [3, 4], [5, 6]])

print(a.shape)
print(b.shape)
np.dot(a, b)

(2,)
(3, 2)


ValueError: shapes (2,) and (3,2) not aligned: 2 (dim 0) != 3 (dim 0)

In [7]:
a = np.array([7, 8])
b = np.array([[1, 2, 3], [4, 5, 6]])

print(a.shape)
print(b.shape)
np.dot(a, b)

(2,)
(2, 3)


array([39, 54, 69])

In [9]:
a = np.array([[7], [8]])
b = np.array([1, 2])

print(a.shape)
print(b.shape)
np.dot(a, b)

(2, 1)
(2,)


ValueError: shapes (2,1) and (2,) not aligned: 1 (dim 1) != 2 (dim 0)

In [11]:
a = np.array([[7], [8]])
b = np.array([[1, 2]])

print(a.shape)
print(b.shape)
np.dot(a, b)

(2, 1)
(1, 2)


array([[ 7, 14],
       [ 8, 16]])

In [18]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def relu(x):
    return np.maximum(x, 0)

def identity_function(x):
    return x

def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    return network

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)
    
    return y

network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
y

array([0.31682708, 0.69627909])

In [19]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y